format: "1"

project:
  name: watcho
  slug: watcho
  web: https://github.com/BlueSkyInnovations/watcho

components:
  - name: watcho
    filemask: locales/*.json
    template: locales/en.json
    new_base: locales/en.json
    file_format: i18next
    source_language: en
    license: MIT
